### ISSUE TITLE
Certificate Management in Web Gui still having issues: 8.8.9

### ISSUE THREAD

**Issue by extremeskillz** [Zimbra/adminguide#74]
Hi,
Not sure if this is the right section for this but I'm running Zimbra 8.8.9 OSE and to date the Web GUI cert manager does not work. Running on top of Ubuntu 16.04lts, We are using internal certs as our "Commercial Certs" for our system and it worked fine in the older versions of Zimbra. I tend to keep my versions up to date and ever since version 8 the GUI continues to be not work when managing or install certs from internal CA. Long story short we use our Zimbra main internally for our users and it works fine with internal certs from our PFsense firewall.  I know its been a bug for a long time and would like to see it fixed.

**Comment by extremeskillz** [comment]
As an update: I can make this work in the CLI no issue using the wiki but for others who don't have the skill to figure it out the web gui does need to be fixed.

**Comment by mogsdad** [comment]
Conversation not relevant to adminguide repo.
